name: Checks

on:
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - uses: actions/setup-node@v2
        with:
          node-version: '18.x'
      - name: Setup env
        run: npm ci
      - name: Check lint
        run: npm run lint
      - name: Check tests
        run: npm run test
